version = 1

# cabal requires the first line in the file to be the `cabal-version` field.
# The license header needs to be added after which looks weird; hence, we are
# specifying the license for `*.cabal` files here.
[[annotations]]
path = "**/*.cabal"
SPDX-FileCopyrightText = "2025 Sören Tempel <soeren+git@soeren-tempel.net>"
SPDX-License-Identifier = "GPL-3.0-only"

# We don't want to force comment headers for test files.
[[annotations]]
path = "qute-syntax/test/golden/*.qbe"
SPDX-FileCopyrightText = "2025 Sören Tempel <soeren+git@soeren-tempel.net>"
SPDX-License-Identifier = "Unlicense"

# We don't want to force comment headers for test files.
[[annotations]]
path = "qute-symex/test/golden/*.qbe"
SPDX-FileCopyrightText = "2025 Sören Tempel <soeren+git@soeren-tempel.net>"
SPDX-License-Identifier = "Unlicense"

# Machine-generated files as obtained by `cproc -emit-qbe`.
[[annotations]]
path = "qute/**/*.qbe"
SPDX-FileCopyrightText = "2025 Sören Tempel <soeren+git@soeren-tempel.net>"
SPDX-License-Identifier = "Unlicense"

# Machine-generated files as obtained by `cproc -emit-qbe`.
[[annotations]]
path = "qute-symex/**/*.qbe"
SPDX-FileCopyrightText = "2025 Sören Tempel <soeren+git@soeren-tempel.net>"
SPDX-License-Identifier = "Unlicense"

# .ktest files are binary files, often generated using KLEE.
[[annotations]]
path = "qute-cli/test/testdata/*.ktest"
SPDX-FileCopyrightText = "2025 Sören Tempel <soeren+git@soeren-tempel.net>"
SPDX-License-Identifier = "Unlicense"

# Guix patches are written by myself, for this repo just unlicense them.
[[annotations]]
path = ".guix/patches/*.patch"
SPDX-FileCopyrightText = "2026 Sören Tempel <soeren+git@soeren-tempel.net>"
SPDX-License-Identifier = "Unlicense"
