;; SPDX-FileCopyrightText: 2025 Sören Tempel <soeren+git@soeren-tempel.net>
;;
;; SPDX-License-Identifier: GPL-3.0-only

(define-module (qute-packages)
  #:use-module (guix) ; XXX: this helps 'current-source-directory'
  #:use-module (guix transformations) ; XXX: needed for 'simple-cc'
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module ((gnu packages c) #:prefix c:)
  #:use-module (gnu packages check)
  #:use-module (gnu packages haskell)
  #:use-module (gnu packages haskell-apps)
  #:use-module (gnu packages haskell-check)
  #:use-module (gnu packages haskell-xyz)
  #:use-module (gnu packages maths)
  #:use-module (gnu packages python)
  #:use-module (guix build-system copy)
  #:use-module (guix build-system haskell)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix packages))

(define %srcdir
  (string-append (current-source-directory) "/../.."))

;; TODO: This can be removed once scc-0.2 has been released.
;; See <https://git.simple-cc.org/scc/commit/575a2d87cac49174b7f53aa6ac5f9186c2165697.html>.
(define-public simple-cc
  (let* ((revision "1")
         (patch (string-append %srcdir "/.guix/patches/simple-cc-void-return.patch"))
         (scc-pkg (package-with-extra-patches
                   c:simple-cc
                   (list patch))))
    (package/inherit scc-pkg
      (version (string-append (package-version scc-pkg) "-" revision)))))

;; ktest-tool python script from KLEE for inspecting .ktest file
;; generated by qute-symex(1) from the qute-cli package.
(define-public ktest-tool
  (package/inherit klee
    (name "ktest-tool")
    (build-system copy-build-system)
    (inputs (list python-minimal))
    (native-inputs '())
    (arguments
      (list
        #:phases
        #~(modify-phases %standard-phases
            (add-after 'unpack 'fix-shebang
              (lambda* (#:key inputs #:allow-other-keys)
                (substitute* "tools/ktest-tool/ktest-tool"
                  (("#!/usr/bin/env python3")
                   (string-append
                     "#!"
                     (search-input-file inputs "/bin/python3")))))))
        #:install-plan
        #~'(("tools/ktest-tool/ktest-tool" "bin/ktest-tool"))))
    (home-page "https://klee-se.org")
    (synopsis "Tool for KLEE's ktest test input format")))

(define-public ghc-simple-smt
  (package
    (name "ghc-simple-smt")
    (version "0.9.8")
    (source
     (origin
       (method url-fetch)
       (uri (hackage-uri "simple-smt" version))
       (sha256
        (base32 "0imimkpzbd013gadkg7sc05jr70lffaij4ijzk368iw8xgvgxyf9"))))
    (build-system haskell-build-system)
    (properties '((upstream-name . "simple-smt")))
    (home-page "https://github.com/yav/simple-smt")
    (synopsis "Simple way to interact with an SMT solver process.")
    (description
     "This package provides a simple way to interact with an SMT solver process.")
    (license license:bsd-3)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define-public qute-syntax
  (package
    (name "qute-syntax")
    (version "0.1.0.0")
    (source (local-file (string-append %srcdir "/qute-syntax")
                        "git-checkout"
                        #:recursive? #t))
    (build-system haskell-build-system)
    (inputs (list ghc-9.2))
    (native-inputs
      (list
        c:qbe
        ghc-tasty
        ghc-tasty-hunit
        ghc-tasty-golden))
    (synopsis "Parser library for the QBE intermediate language")
    (description "")
    (home-page "https://git.8pit.net/qute")
    (license (list license:expat license:bsd-2 license:gpl3))))

(define-public qute
  (package
    (name "qute")
    (version "0.1.0.0")
    (source (local-file (string-append %srcdir "/qute")
                        "git-checkout"
                        #:recursive? #t))
    (build-system haskell-build-system)
    (inputs (list ghc-9.2))
    (native-inputs
      (list
        qute-syntax
        ghc-tasty
        ghc-tasty-hunit))
    (synopsis "Analysis library for the QBE intermediate language")
    (description "")
    (home-page "https://git.8pit.net/qute")
    (license (list license:expat license:gpl3))))

(define-public qute-symex
  (package
    (name "qute-symex")
    (version "0.1.0.0")
    (source (local-file (string-append %srcdir "/qute-symex")
                        "git-checkout"
                        #:recursive? #t))
    (build-system haskell-build-system)
    (inputs (list ghc-9.2
                  bitwuzla)) ;needed for 'check.
    (native-inputs
      (list
        qute
        qute-syntax
        ghc-tasty
        ghc-tasty-hunit
        ghc-tasty-golden
        ghc-tasty-quickcheck
        ghc-simple-smt))
    (synopsis "Symbolic executor for the QBE intermediate language")
    (description "")
    (home-page "https://git.8pit.net/qute")
    (license (list license:expat license:gpl3))))

(define-public qute-cli
  (package
    (name "qute-cli")
    (version "0.1.0.0")
    (source (local-file (string-append %srcdir "/qute-cli")
                        "git-checkout"
                        #:recursive? #t))
    (build-system haskell-build-system)
    (inputs (list ghc-9.2))
    (native-inputs
      (list
        qute
        qute-syntax
        qute-symex
        ghc-optparse-applicative
        ghc-tasty-hunit))
    (synopsis "Command line utilities for qute")
    (description "")
    (home-page "https://git.8pit.net/qute")
    (license (list license:gpl3))))
