cabal-version:      3.4
name:               qute-syntax
version:            0.1.0.0
-- synopsis:
-- description:
license:            GPL-3.0-only AND BSD-2-Clause AND MIT
-- license-file:
author:             Sören Tempel
maintainer:         soeren+git@soeren-tempel.net
-- copyright:
category:           Language
build-type:         Simple
-- extra-doc-files:
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    -- other-extensions:
    hs-source-dirs:   src
    default-language: GHC2021

    other-modules:
      Language.QBE.Util,
      Language.QBE.Numbers

    exposed-modules:
      Language.QBE,
      Language.QBE.Types,
      Language.QBE.Parser

    build-depends:
      base,
      parsec,
      containers,
      exceptions

test-suite qute-syntax-test
    import:           warnings
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs

    other-modules:
      Parser,
      Golden,
      Types

    build-depends:
        base,
        qute-syntax,
        parsec,
        process,
        filepath,
        containers,
        tasty        >=1.4.3,
        tasty-hunit  >=0.10,
        tasty-golden >=2.3.5,
